### PR TITLE
Add console for debugging

### PR DESCRIPTION
**Pull request by mikee47**
This PR aims to provide a simple way to direct debug output to the TFT display.
It's an ideal application for hardware scrolling.

Requires `feature/hardware-scrolling` branch of `HardwareSPI`.

todo:

* [x] Implement `Priint` class which handles printing text to display with appropiate scrolling
~~* [ ] Implement back-buffer so display can be scrolled up/down, e.g. using touch input~~
* [x] Add pause function so rapid output can be suspended for reading

### CODE REVIEW

**Comment by mikee47** [comment]
@slaff I've added a Console class and hardware scrolling support to the Graphics library, and updated this PR to demonstrate its use. Would you give it a try out?

**Comment by slaff** [comment]
> Would you give it a try out?

Works great! Thank you @mikee47.

**Comment by slaff** [comment]
@mikee47 Can you merge `feature/hardware-scrolling` into your develop branch and create a PR with the latest HardwareSPI version for Sming?

**Comment by mikee47** [comment]
@slaff HardwareSPI develop was added in https://github.com/SmingHub/Sming/pull/2406

**Comment by mikee47** [comment]
Note that scrolling only works in full-screen. I'm developing it further to support scrolling within a fixed header/footer but that's more involved.

**Pull request merged**
